### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by trostli** [omc/heroku-kibana#1]
When I launch the app and provide a custom ElasticSearch URL I get 'Application Error' on Heroku

**Comment by nz** [comment]
Thanks I'll do some more testing on that. It's possible that pushing up an empty commit may trigger a slug rebuild as a quick fix to get around that.

**Comment by trostli** [comment]
Turns out it was as simple as just turning on a dyno. When launched to heroku the app doesn't turn one on by default.
