### ISSUE TITLE
cant install kibana-4.6.2

### ISSUE THREAD

**Issue by djholly123** [omc/heroku-kibana#3]
Hi 
apologies if being dumb here

I am trying to install using you build pack
DOWNLOAD_URL=https://artifacts.elastic.co/downloads/kibana/kibana-5.0.0-linux-x86_64.tar.gz

I get this error :
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
POST git-receive-pack (433 bytes)

remote: Compressing source files... done.        
remote: Building source:        

remote: 
remote: -----> kibana app detected        
remote: -----> Installing Kibana...        
remote:        downloading https://artifacts.elastic.co/downloads/kibana/kibana-5.0.0-linux-x86_64.tar.gz        
remote:        verifying against https://artifacts.elastic.co/downloads/kibana/kibana-5.0.0-linux-x86_64.tar.gz.sha1.txt        
remote: sha1sum: kibana-5.0.0-linux-x86_64.tar.gz.sha1.txt: 1: improperly formatted SHA1 checksum line        
remote: sha1sum: kibana-5.0.0-linux-x86_64.tar.gz.sha1.txt: 2: improperly formatted SHA1 checksum line        
remote: sha1sum: kibana-5.0.0-linux-x86_64.tar.gz.sha1.txt: no properly formatted SHA1 checksum lines found        
remote:  !     Push rejected, failed to compile kibana app.        
remote: 

remote:  !     Push failed        
remote: Verifying deploy...        
remote: 
remote: !	Push rejected to mc-kibana-test1.        

remote:

**Comment by robsears** [comment]
That's because https://artifacts.elastic.co/downloads/kibana/kibana-5.0.0-linux-x86_64.tar.gz.sha1.txt doesn't point to a valid checksum.

Try changing lines 56-58:

```
  echo "verifying against ${DOWNLOAD_URL}.sha1" | indent
  $download "${DOWNLOAD_URL}.sha1"
  $verify "${KIBANA_PACKAGE}.sha1"
```

**Comment by djholly123** [comment]
Thanks 
got round that now its running but kibana is trying to talk to localhost despite setting the ELASTICSERACH_URL or BONSAI_URL

kibana.yml is not edited

**Comment by robsears** [comment]
The ELASTICSEARCH_URL environment variable is used during slug compilation. In order to change or set it, you need to recompile the slug. The most common way to do that is by pushing an empty commit like so:

```
git commit --allow-empty -m "Recompile slug"
```

Then push the change to the Heroku app.

**Comment by djholly123** [comment]
thanks I tried that but still get this

ELASTICSEARCH_URL is set in heroku config

**Comment by djholly123** [comment]
this being  Unable to connect to Elasticsearch at http://localhost:9200.

**Comment by djholly123** [comment]
Hi 
I have tried many options but it does not seem to be editing the kibana.yml file app always tries to start pointing at localhost

install works ok from https://download.elastic.co/kibana/kibana/kibana-4.6.2-linux-x86_64.tar.gz
any help appreciated
