### ISSUE TITLE
Outdated URL format for MD5 checksum

### ISSUE THREAD

**Issue by aendra-rininsland** [omc/heroku-kibana#4]
Installing a newer version of Kibana fails because `bin/compile` expects the MD5 checksum to end in .txt, whereas it now does not include that extension.

https://artifacts.elastic.co/downloads/kibana/kibana-5.1.2-linux-x86_64.tar.gz.sha1.txt -- 404
https://artifacts.elastic.co/downloads/kibana/kibana-5.1.2-linux-x86_64.tar.gz.sha1 -- 200

**Comment by robsears** [comment]
Closing outdated. This is fixed in the current [5.4.3 branch](https://github.com/omc/heroku-kibana/tree/v5.4.3).
