### ISSUE TITLE
I am facing 'Unable to connect to Elasticsearch at https://kibanauser:kibanapass@host.region.bonsai.io/:443.'

### ISSUE THREAD

**Issue by bvenkata** [omc/heroku-kibana#5]
I installed elasticsearch as well but i dont why its throwing above error

**Comment by robsears** [comment]
That is not a valid URL to an Elasticsearch cluster. When the Kibana app is created, you have the option to supply a link to a private cluster (hosted elsewhere, a localhost will not work), or you can leave it blank to have a Bonsai cluster provisioned.

We've done some work to clarify this and make the code a little less fragile. Mind trying again using the [5.4.3 branch](https://github.com/omc/heroku-kibana/tree/v5.4.3)?
