### ISSUE TITLE
Version issues, how to resolve

### ISSUE THREAD

**Issue by jakeywan** [omc/heroku-kibana#6]
Hi there, I'm trying to use the 1 click deploy of Kibana and I'm getting some kind of version issue. How can I resolve this? Thanks!

<img width="1331" alt="screen shot 2017-09-14 at 6 08 51 pm" src="https://user-images.githubusercontent.com/1462496/30462070-f38fcc60-9977-11e7-8ad7-6bff4a56ccfb.png">

**Comment by robsears** [comment]
Hey @jakey-wan-kenobi that's a version mismatch. Bonsai is currently defaulting to Elasticsearch v5.4.3, and the Kibana version needs to match that. Want to try using the [5.4.3 branch](https://github.com/omc/heroku-kibana/tree/v5.4.3) to deploy? Make sure to read the note about authentication. Thanks!
